### ISSUE TITLE
Grammar for AnyWord token

### ISSUE THREAD

**Issue by roddar92** [ExpandingDev/JSGFKit#1]
Dear colleagues,

I'm trying to make a grammar for anyWord token. Now it looks like this:

`<any_word> = (a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|r|s|t|u|v|w|x|y|z)+;`
`<rule> = <any_word>* a b <any_word>* c;`

But anyWord doesn't work in the last rule ('please a b c', 'a, b please c' etc.)
How could I fix my rule for correct working? Do '*' and '+' operators work correctly?

Sincerely yours,
Daria

**Comment by ExpandingDev** [comment]
**JSGF does not do character-by-character matching, only word-by-word matching.** 
An example input that would match your grammar would be: `h e l l o a b w o r l d c` Where each character is treated as a separate word.

Additionally, I hope you are not going to feed this to speech recognition software, it'll decrease your accuracy. JSGF was meant to make the number of words possibly spoken small to increase recognition accuracy (less possible combinations means higher accuracy), and this grammar instead makes a very large number of possible combinations.
